// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzGcpQVnpBJt98YLgau69QeCJRMlyKlFU',
    appId: '1:964020889135:web:353836322e2ac3317fc8da',
    messagingSenderId: '964020889135',
    projectId: 'treino-44482',
    authDomain: 'treino-44482.firebaseapp.com',
    storageBucket: 'treino-44482.appspot.com',
    measurementId: 'G-8SKJXH0XTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi6o1nyCcP4RWcgaPlYAgeFptX8ZminjA',
    appId: '1:964020889135:android:9c52d118ee279fce7fc8da',
    messagingSenderId: '964020889135',
    projectId: 'treino-44482',
    storageBucket: 'treino-44482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAd4EQESy1P8ubsc4xIflwRX5WvMT5XlY',
    appId: '1:964020889135:ios:032fbec50e7a1d607fc8da',
    messagingSenderId: '964020889135',
    projectId: 'treino-44482',
    storageBucket: 'treino-44482.appspot.com',
    iosBundleId: 'com.example.treinoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAd4EQESy1P8ubsc4xIflwRX5WvMT5XlY',
    appId: '1:964020889135:ios:032fbec50e7a1d607fc8da',
    messagingSenderId: '964020889135',
    projectId: 'treino-44482',
    storageBucket: 'treino-44482.appspot.com',
    iosBundleId: 'com.example.treinoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzGcpQVnpBJt98YLgau69QeCJRMlyKlFU',
    appId: '1:964020889135:web:80a835aa399592f97fc8da',
    messagingSenderId: '964020889135',
    projectId: 'treino-44482',
    authDomain: 'treino-44482.firebaseapp.com',
    storageBucket: 'treino-44482.appspot.com',
    measurementId: 'G-3GBHS1QZ5G',
  );
}
